FROM golang:1.17 as Build

# Install xk6
RUN go install go.k6.io/xk6/cmd/xk6@latest


# Build the k6 binary
RUN xk6 build --output /bin/k6 --with github.com/grafana/xk6-output-prometheus-remote@v0.0.8

FROM loadimpact/k6:latest
COPY --from=Build /bin/k6 /bin/k6